#!/bin/bash

export AWS_ACCESS_KEY_ID=AKIAJKZN5DXUYODHENKA
export AWS_SECRET_ACCESS_KEY=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
export AWS_DEFAULT_REGION=eu-west-2

SUBFOLDER="uk/explore/kings-cross"

S3STAGING="s3://samsung-staging.cheil.uk/"

# CloudFront ids used to invalidate distributions
CFSTAGING="E2ZJZEBZFX3D8F" # d1bb30i8nznsls.cloudfront.net

if [ $# -ne 1 ]; then
    echo "usage: ./dodeploy [staging|live]"
    exit 1
fi


echo ""
echo ""
echo "YOU ARE DEPLOYING THE ... >>> ${SUBFOLDER} <<< ... CONTENT"
echo ""
echo ""


case "$1" in
"staging")
    echo "dry run deploy to staging ..."
    #
	aws s3 sync --dryrun build/$SUBFOLDER $S3STAGING$SUBFOLDER --exclude "*" --include "css/*" --include "js/*" --include "home-of-innovation/*" --exclude "*DS_Store" 
	#
	read -p "Are you sure you want to deploy? " -n 1 -r
	echo    # (optional) move to a new line
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
	    # do it
	    echo "deploying to staging ..."
		aws s3 sync build/$SUBFOLDER $S3STAGING$SUBFOLDER --exclude "*" --include "css/*" --include "js/*" --include "home-of-innovation/*" --exclude "*DS_Store" 
		echo "done"

		echo "********************************************"
		echo "*** INVALIDATING CLOUDFRONT DISTRIBUTION ***"
		echo "********************************************"

		aws cloudfront create-invalidation --distribution-id $CFSTAGING --paths /$SUBFOLDER/*

	fi
    ;;
"live")
    echo "THERE IS NO LIVE ENVIRONMENT :)"
    ;;
*)
    echo "invalid - usage: ./dodeploy [staging|live]"
    ;;
esac
